### ISSUE TITLE
Character icons not working. #Android

### ISSUE THREAD

**Issue by vrnDhmn** [prscX/react-native-chip-view#1]
When we pass `icon={true}` prop, the character icons are not showing in case of Android.

**Comment by prscX** [comment]
Thanks @nuravdhiman for raising the issue.

Coming weekend I will look into this and will share the results.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @nuravdhiman, I have fixed and pushed a release `V0.0.2`. Let me know in case you still face the same issue.

Thanks
</ Pranav>
