### ISSUE TITLE
MaterialInput lib wrap

### ISSUE THREAD

**Issue by Noitidart** [prscX/react-native-chip-view#2]
Thank you sir so much for creating another awesome lib. I actually just rolled my own a couple of months ago. But i was hoping to use this - https://github.com/pchmn/MaterialChipsInput

I was wondering, as you might have some expertise in binding native libs to RN, would you be able to bind https://github.com/pchmn/MaterialChipsInput for us please? No rush just a humble request if you have time. :)

**Comment by prscX** [comment]
Thanks @Noitidart for sharing the library.

[react-native-chip-view](https://github.com/prscX/react-native-chip-view) just provides a Material Chip in order to show specific information.

Shared library is really good. Earlier I have tried to look for its iOS compatible library but was unable to find. Do you know any similar library for iOS? because building just for Android will not fulfill end user needs.  

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
That's true. I don't know of one yet for iOS. :( I am making an Android only app so this would be useful for me. But no worries I'll learn how to native bridge. I have been baaaadly wanting to learn that.

I am hoping to create a native multi slider view and bridge these two:

Android - https://github.com/apptik/MultiSlider

iOS - https://github.com/yonat/MultiSlider

Is there somewhere easy you would recommend for me a person with no native experience (js only) to get a baby walk thru step by step to do a bridge for RN?

**Comment by prscX** [comment]
Thanks @Noitidart for sharing the MultiSlider. Both libraries look promising, I will plan to work on this in coming days based on my present workload.

Can I close this thread? in order to focus on the raised issues.

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Thank you sir very much for asking. You are too kind. Yes please let's close this topic.

Is it possible if I can peer work with you on the multislider. I badly want to learn how to bridge native modules. Right now it seems you are all alone. I want to help you provide such great libs. I am comfortable if you want to connect to my computer via any remote software. I have teamviewer. Or if you are comfortable if you would allow me to connect to you. Whichever way. If neither is comfortable no problem I understand, but in this case may you please link me to some resources to learn. the native guides on react-native docs didn't help me. :(

**Comment by prscX** [comment]
Sure Definitely, it would be my pleasure to work with you on the library. Meantime you can go through below repo in order to get some hands on:

[awesome-react-native-native-modules/](https://github.com/prscX/awesome-react-native-native-modules)

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Thank you very much!! I will try this repo out! :D
