### ISSUE TITLE
it wont take titleStyle prop

### ISSUE THREAD

**Issue by purushottamparajuli** [prscX/react-native-chip-view#3]

**Comment by prscX** [comment]
Thanks @purushottamparajuli for raising the issue.

It was a minor issue, I have fixed and pushed a release [v0.0.5](https://github.com/prscX/react-native-chip-view/releases/tag/v0.0.5) with the same.

Can you please install latest version and verify the same. Let me know in case you still face the same issue.

Thanks
</ Pranav >
